# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  main:
    name: Main module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.19'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -race ./...

  bbolt:
    name: bbolt eventstore
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build
        run: cd eventstore/bbolt && go build -v ./...

      - name: Test
        run: cd eventstore/bbolt && go test -v -race ./...
       
  sql:
    name: sql eventstore
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.19'

      - name: Build
        run: cd eventstore/sql && go build -v ./...

      - name: Test
        run: cd eventstore/sql && go test -v -race ./...

  esdb:
    name: esdb eventstore
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build
        run: cd eventstore/esdb && go build -v ./...

      - name: Test
        run: cd eventstore/esdb && go test -v -race ./...

  sqlsnapshot:
    name: sql snapshotstore
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.19'

      - name: Build
        run: cd snapshotstore/sql && go build -v ./...

      - name: Test
        run: cd snapshotstore/sql && go test -v -race ./...
